### PR TITLE
Add MapFlag

### PR DESCRIPTION
**Pull request by Andavin**
Signed-off-by: Mark <33119mark@gmail.com>

I found a use for a MapFlag in one of my projects I was working on. Just a useful utility for more complex flag setup.

### CODE REVIEW

**Comment by Andavin** [comment]
I don't understand. What about this would fail the build? The coding style? That's all I think that I gathered from the details.

**Comment by gabizou** [comment]
It says in the log: 
```
[ant:checkstyle] /home/travis/build/sk89q/WorldGuard/worldguard-legacy/src/main/java/com/sk89q/worldguard/protection/flags/MapFlag.java:4:1: Disallowed import - org.apache.commons.lang.StringUtils.
```

**Comment by me4502** [comment]
Does this still function correctly in the latest versions of WorldGuard? If so, I'll merge it.

**Comment by Andavin** [comment]
This does indeed compile with the latest version of WorldGuard and as it is basically a small string parser there doesn't seem to be any other possibilities for version incompatibility.

**Comment by me4502** [comment]
Thanks

**Pull request merged**
