### PR TITLE
Make flag list more readable

### PR DESCRIPTION
**Pull request by Blacksheep92**
Alphabetical sorting and color differentiation.

### CODE REVIEW

**Comment by wizjany** [comment]
originally the flags were given in an order grouped by their function, which made it easier to find a flag if you knew what kind of thing you were looking for but not the name. alphabetical order only helps to find a flag if you know the first part of the name already.

**Comment by Blacksheep92** [comment]
I havn't noticed any meaningful groups in all the years of use.
Perhaps these groups should be name and better separated from each other?

**Comment by wizjany** [comment]
kind of like this although over the years some things have been badly placed.

http://i.imgur.com/GKyWBHZ.png

you can see some distinctions between build flags, membership-based, mobs/explosions, natural growth, liquid/spread, etc etc.

as you said it's not completely obvious since they aren't separated or labeled, but they are there if you know to look for them.

**Comment by Blacksheep92** [comment]
Ok, on closer inspection it makes sense.

My intention was to find a known flag faster. (But this could be solved by tab completion)

But the color separation is still a useful simplification:
http://i.imgur.com/6FitMJl.png

**Comment by wizjany** [comment]
colors are nice, definitely an improvement over the previous block of red.
tab completion would also be nice lol.

**Comment by Blacksheep92** [comment]
I've adapted the Pullrequest.
Only the color adjustments are included.

**Comment by TomyLobo** [comment]
why is that even crammed into so few lines in the first place?
I think it should be one per line, with comments indicating the sections.

**Comment by wizjany** [comment]
because this was written before minecraft had chat scrollback. there were probably also a lot less flags to worry about as well. and like i said the sections aren't really well defined.

**Comment by TheMolkaPL** [comment]
This should be paginated imo. Also colors can be helpful to separate the sections - eg. red for building flags, green for spawning, etc.

**Comment by wizjany** [comment]
well then make a PR @TheMolkaPL

**Comment by wizjany** [comment]
merged, thanks.

**Pull request closed without merging**
