### PR TITLE
Слияние с основными исходниками.

### PR DESCRIPTION
**Pull request by RainbowKiwiFOX**

### CODE REVIEW

**Comment by q220** [comment]
What is this supposed to be? The main branch is written in English, not Cyrillic. If you have something to contribute or want to make a PR please write your code and comments in English.

**Comment by ewized** [comment]
@q220 Its russian and I think this was a mistake as he translates plugins to Russian, if you look on their profile.

**Comment by RainbowKiwiFOX** [comment]
Sorry, it's mistake. :)

Could you bring the localization file? It would be very convenient.

P. S. Excuse me for my bad English, I'm Russian.

**Comment by TomyLobo** [comment]
Well, you could make a PR with those russian readmes as separate files (README.ru or README.ru.md or something)
As for the in-game text, afaik there is currently no localization system in place.
You could of course make a PR for one.

**Pull request closed without merging**
