### PR TITLE
Issue with plugin (please add issues tab on github)

### PR DESCRIPTION
**Pull request by MentosPL**
When i have more than 48 plugins, Worldguard Don't want be loaded:

`[00:57:30] [Server thread/INFO]: [ViaVersion] Hooking into ProtocolSupport, to prevent issues!
[00:57:31] [Server thread/ERROR]: Could not load 'plugins\worldguard-legacy-6.2.2-SNAPSHOT-dist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandsManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 6 more
[00:57:31] [Server thread/INFO]: [Elevators] Loading Elevators v1.2.8`

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
You need to have WorldEdit installed.

**Comment by MentosPL** [comment]
I  have WorldEdit ;-; WorldEdit always run propertly, but worldguard think, there no Worldedit when i have more than 48 plugins.

**Comment by TheMolkaPL** [comment]
Is your Bukkit modded?

**Comment by MentosPL** [comment]
Im using traditional Spigot ;-; 1.12.2

**Comment by DarkArc** [comment]
I can assure you WorldEdit is not present or the version of WorldEdit (or possibly WorldGuard) you have is out of date. FYI, we have an external bug tracker for reporting issues as well: http://dev.enginehub.org/youtrack/dashboard?id=36a64219-5d44-4c5d-8b3f-91271f907bfc

**Comment by MentosPL** [comment]
you can give me links to recomended and latest build of WorldEdit and Worldguard?

**Comment by DarkArc** [comment]
http://builds.enginehub.org/job/worldedit/9945/download/worldedit-bukkit-6.1.9-SNAPSHOT-dist.jar
http://builds.enginehub.org/job/worldguard/9934/download/worldguard-legacy-6.2.2-SNAPSHOT-dist.jar

Make sure you remove any old copies of WorldEdit & WorldGuard. Also if you're using FastAsyncWorldEdit, or something similar, that is unsupported.

**Comment by MentosPL** [comment]
I had these plugins, I put those plugins you gave me, i removed Worldguard and WorldEdit folders, and still when i have more than 48 plugins worldGuard are don't loading, but worldEdit running propertly, i don't understand this.

**Pull request closed without merging**
