### PR TITLE
Reset player saturation and exhaustion for the /heal command.

### PR DESCRIPTION
**Pull request by kosakriszi**
This is a pretty simple PR, it modifies the /heal command to reset the target's saturation and exhaustion levels, so you don't immediately start losing hunger after a /heal.

### CODE REVIEW

**Comment by kosakriszi** [comment]
Looks like there's some wonky permission denied errors in the Travis system.

**Comment by TomyLobo** [comment]
Maybe these should be flags? what do the others think?
Maybe a flag for health as well that defaults to true only if none of the others are set?
"/heal -hfe" or something

btw, there shouldn't be any merge commits in your PR. please rebase it.

**Comment by DarkArc** [comment]
I'm fine with just merging this as is. This wasn't updated because the command was deprecated in favor of CommandBook's version, which does pretty much exactly the same thing. Updating saturation is a reasonable default behavior. 
		
        
		
		 ---- On Wed, 06 Jan 2016 14:03:13 -0800  notifications@github.com  wrote ----Maybe these should be flags? what do the others think?
Maybe a flag for health as well that defaults to true only if none of the others are set?
"/heal -hfe" or something
btw, there shouldn't be any merge commits in your PR. please rebase it.

**Comment by TomyLobo** [comment]
oh right, i forgot. no objections to merging then

**Comment by kosakriszi** [comment]
I'd love to rebase, but I have no idea how to do it properly, and Google honestly isn't helping me.

**Comment by DarkArc** [comment]
@kosakriszi here, see if you're interested in learning to rebase, see if this helps you: http://haxing.ninja/tutorial/git/rebase/. I quickly wrote up a tutorial for git rebasing, particularly for situations like this, it could stand some improvement, but it should be useful none the less.

**Comment by kosakriszi** [comment]
Thank you for the guide, I will remake this pull request, since I've sufficiently messed this up with my fooling around

**Pull request closed without merging**
